# Generated by Django 5.0.3 on 2024-03-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_check_dttm_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='evsp2_clients',
        ),
    ]
