# Generated by Django 5.0.3 on 2024-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_confkeys_alter_variables_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variables',
            old_name='interval',
            new_name='value',
        ),
        migrations.AddField(
            model_name='variables',
            name='variable',
            field=models.CharField(blank=True, max_length=64, verbose_name='기준변수'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='group',
            field=models.CharField(blank=True, max_length=64, verbose_name='적용대상'),
        ),
        migrations.AlterModelTable(
            name='confkeys',
            table='evsp2_confkeys',
        ),
        migrations.AlterModelTable(
            name='variables',
            table='evsp2_variables',
        ),
    ]
